apiVersion: batch/v1
kind: Job
metadata:
  name: vicreg-wnae-job
  namespace: axol1tl
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: trainer
          image: gitlab-registry.nrp-nautilus.io/mquinnan/axol1tl-hub:axol1tl-container
          imagePullPolicy: Always
          volumeMounts:
            - name: axovol
              mountPath: /axovol
          workingDir: /axovol/l1ad

          command:
            - "/bin/bash"
            - "-c"
            - |
              set -e
              cd /axovol/l1ad
              git pull
              pip install pot --quiet
              mkdir -p /axovol/l1ad/checkpoints/vicreg_wnae
              python -u scripts/train_vicreg_wnae.py --config config/vicreg_wnae_config.yaml | tee /axovol/l1ad/checkpoints/vicreg_wnae/training.log

          resources:
            requests:
              cpu: "8"
              memory: "32Gi"
              nvidia.com/gpu: 2
            limits:
              cpu: "8"
              memory: "32Gi"
              nvidia.com/gpu: 2
      volumes:
        - name: axovol
          persistentVolumeClaim:
            claimName: axovol
