apiVersion: batch/v1
kind: Job
metadata:
  name: vicreg-job
  namespace: axol1tl
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: tuner
          image: python:3.10-slim
          imagePullPolicy: Always
          volumeMounts:
            - name: axovol
              mountPath: /axovol
          workingDir: /axovol/l1ad

          command:
            - "/bin/bash"
            - "-c"
            - |
              set -e
              python -m pip install --no-cache-dir -r requirements.txt
              python -m pip install numpy==1.23.5
              python -m pip install scipy==1.13.1
              python -u train_vicreg.py --config config/config.yaml | tee vicreg_training.log

          resources:
            requests:
              cpu: "8"
              memory: "32Gi"
              nvidia.com/gpu: 2
            limits:
              cpu: "8"
              memory: "32Gi"
              nvidia.com/gpu: 2
      volumes:
        - name: axovol
          persistentVolumeClaim:
            claimName: axovol
