apiVersion: v1
kind: Pod
metadata:
  name: wnae-pod
spec:
  containers:
  - name: gpu-container
    image: gitlab-registry.nrp-nautilus.io/mquinnan/axol1tl-hub:axol1tl-container
    #image: gitlab-registry.nrp-nautilus.io/mquinnan/axol1tl-hub:axol1tl-container
    # image: gitlab-registry.nrp-nautilus.io/mquinnan/axol1tl-hub:axo-env-gpu-conda
    # image: gitlab-registry.nrp-nautilus.io/nrp/scientific-images/python:cuda-v1.4.1
    command: ["bash", "-c", "sleep 1d"]
    resources:
      limits:
        nvidia.com/gpu: 1
        memory: 30Gi
        cpu: 4
      requests:
        nvidia.com/gpu: 1
        memory: 30Gi
        cpu: 3
    volumeMounts:
    - mountPath: /axovol
      name: axovol
  restartPolicy: Never
  volumes:
    - name: axovol
      persistentVolumeClaim:
        claimName: axovol
